# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
 build:
   docker:
     # specify the version you desire here
     - image: circleci/mongo:3
     
     # Specify service dependencies here if necessary
     # CircleCI maintains a library of pre-built images
     # documented at https://circleci.com/docs/2.0/circleci-images/
     # - image: circleci/postgres:9.4

   working_directory: ~/repo

   environment:
     # Customize the JVM maximum heap limit
     MAVEN_OPTS: -Xmx3200m
   
   steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.12.0
      - run:
          name: Build application Docker image
          command: |
            docker build -t 463442625423.dkr.ecr.us-east-2.amazonaws.com/yello-team:$CIRCLE_SHA1 .
            docker build -t 463442625423.dkr.ecr.us-east-2.amazonaws.com/yello-team:latest .
      - deploy:
          name: Push Docker image
          command: |
          docker run -d -p 8080:8080 --name yello-team 463442625423.dkr.ecr.us-east-2.amazonaws.com/yello-team:$CIRCLE_SHA1; sleep 10
          chmod +x ./deploy.sh
          ./deploy.sh
